import { describe, it, expect } from 'vitest'
import { renderConfig, rateLimitZoneName } from './render.js'
import type { Route, FileRoute } from '@unginx/shared'

const STAGING = '/data/staging'

const baseRoute: Route = {
  id: 'aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee',
  group_id: null,
  name: 'Test API',
  path: '/api',
  upstream_host: 'localhost',
  upstream_port: 3000,
  upstream_scheme: 'http',
  strip_prefix: true,
  websocket: false,
  enabled: true,
  description: null,
  advanced_json: {},
  created_at: 1700000000000,
  updated_at: 1700000000000,
}

const baseFileRoute: FileRoute = {
  id: 'ffffffff-1111-2222-3333-444444444444',
  group_id: null,
  name: 'Docs',
  path: '/docs',
  folder_path: '/data/sites/docs',
  index_files: 'index.html',
  dir_listing: false,
  try_files: null,
  spa_mode: false,
  enabled: true,
  description: null,
  advanced_json: {},
  created_at: 1700000000000,
  updated_at: 1700000000000,
}

describe('renderConfig — routes.conf', () => {
  it('generates a proxy location block', () => {
    const { 'routes.conf': conf } = renderConfig({ routes: [baseRoute], fileRoutes: [] }, STAGING)
    expect(conf).toContain('location /api {')
    expect(conf).toContain(`set $unginx_route_id "${baseRoute.id}";`)
    expect(conf).toContain('proxy_pass http://localhost:3000;')
    expect(conf).toContain('proxy_http_version 1.1;')
    expect(conf).toContain('proxy_set_header Host')
  })

  it('omits disabled routes', () => {
    const disabled = { ...baseRoute, enabled: false }
    const { 'routes.conf': conf } = renderConfig({ routes: [disabled], fileRoutes: [] }, STAGING)
    expect(conf).not.toContain('location /api')
  })

  it('uses https scheme when configured', () => {
    const httpsRoute = { ...baseRoute, upstream_scheme: 'https' as const }
    const { 'routes.conf': conf } = renderConfig({ routes: [httpsRoute], fileRoutes: [] }, STAGING)
    expect(conf).toContain('proxy_pass https://localhost:3000;')
  })

  it('adds WebSocket headers when websocket=true', () => {
    const wsRoute = { ...baseRoute, websocket: true }
    const { 'routes.conf': conf } = renderConfig({ routes: [wsRoute], fileRoutes: [] }, STAGING)
    expect(conf).toContain('proxy_set_header Upgrade')
    expect(conf).toContain('proxy_set_header Connection')
  })

  it('emits advanced body size directive', () => {
    const r = { ...baseRoute, advanced_json: { client_max_body_size_mb: 50 } }
    const { 'routes.conf': conf } = renderConfig({ routes: [r], fileRoutes: [] }, STAGING)
    expect(conf).toContain('client_max_body_size 50m;')
  })

  it('emits advanced timeout directives', () => {
    const r = {
      ...baseRoute,
      advanced_json: { proxy_read_timeout_s: 120, proxy_connect_timeout_s: 10 },
    }
    const { 'routes.conf': conf } = renderConfig({ routes: [r], fileRoutes: [] }, STAGING)
    expect(conf).toContain('proxy_read_timeout 120s;')
    expect(conf).toContain('proxy_connect_timeout 10s;')
  })

  it('emits request and response header directives', () => {
    const r = {
      ...baseRoute,
      advanced_json: {
        request_headers: [{ name: 'X-Custom', value: 'req-val' }],
        response_headers: [{ name: 'X-Frame-Options', value: 'DENY' }],
      },
    }
    const { 'routes.conf': conf } = renderConfig({ routes: [r], fileRoutes: [] }, STAGING)
    expect(conf).toContain('proxy_set_header X-Custom "req-val";')
    expect(conf).toContain('add_header X-Frame-Options "DENY";')
  })

  it('emits limit_req for rate-limited routes', () => {
    const r = { ...baseRoute, advanced_json: { rate_limit_req_per_sec: 10 } }
    const { 'routes.conf': conf } = renderConfig({ routes: [r], fileRoutes: [] }, STAGING)
    const zone = rateLimitZoneName(r.id)
    expect(conf).toContain(`limit_req zone=${zone}`)
  })

  it('produces a header comment', () => {
    const { 'routes.conf': conf } = renderConfig({ routes: [], fileRoutes: [] }, STAGING)
    expect(conf).toContain('AUTO-GENERATED by unginx')
  })
})

describe('renderConfig — files.conf', () => {
  it('generates an alias location block', () => {
    const { 'files.conf': conf } = renderConfig({ routes: [], fileRoutes: [baseFileRoute] }, STAGING)
    expect(conf).toContain('location /docs {')
    expect(conf).toContain(`set $unginx_route_id "${baseFileRoute.id}";`)
    expect(conf).toContain('alias /data/sites/docs/;')
    expect(conf).toContain('index index.html;')
    expect(conf).toContain('autoindex off;')
  })

  it('omits disabled file routes', () => {
    const disabled = { ...baseFileRoute, enabled: false }
    const { 'files.conf': conf } = renderConfig({ routes: [], fileRoutes: [disabled] }, STAGING)
    expect(conf).not.toContain('location /docs')
  })

  it('adds trailing slash to folder_path if missing', () => {
    const { 'files.conf': conf } = renderConfig(
      { routes: [], fileRoutes: [{ ...baseFileRoute, folder_path: '/data/sites/docs' }] },
      STAGING
    )
    expect(conf).toContain('alias /data/sites/docs/;')
  })

  it('emits SPA try_files when spa_mode=true', () => {
    const spa = { ...baseFileRoute, spa_mode: true }
    const { 'files.conf': conf } = renderConfig({ routes: [], fileRoutes: [spa] }, STAGING)
    expect(conf).toContain('try_files $uri $uri/ /index.html;')
  })

  it('emits custom try_files when set', () => {
    const fr = { ...baseFileRoute, try_files: '/fallback.html' }
    const { 'files.conf': conf } = renderConfig({ routes: [], fileRoutes: [fr] }, STAGING)
    expect(conf).toContain('try_files $uri $uri/ /fallback.html;')
  })

  it('enables directory listing', () => {
    const fr = { ...baseFileRoute, dir_listing: true }
    const { 'files.conf': conf } = renderConfig({ routes: [], fileRoutes: [fr] }, STAGING)
    expect(conf).toContain('autoindex on;')
  })
})

describe('renderConfig — nginx.conf (staging test config)', () => {
  it('produces a complete nginx config with events and http blocks', () => {
    const { 'nginx.conf': conf } = renderConfig({ routes: [baseRoute], fileRoutes: [] }, STAGING)
    expect(conf).toContain('events {')
    expect(conf).toContain('http {')
    expect(conf).toContain('server {')
  })

  it('includes staging dir fragments', () => {
    const { 'nginx.conf': conf } = renderConfig({ routes: [], fileRoutes: [] }, STAGING)
    expect(conf).toContain(`include ${STAGING}/routes.conf;`)
    expect(conf).toContain(`include ${STAGING}/files.conf;`)
  })

  it('declares the log_format at http level', () => {
    const { 'nginx.conf': conf } = renderConfig({ routes: [baseRoute], fileRoutes: [] }, STAGING)
    expect(conf).toContain('log_format unginx_combined')
  })

  it('puts limit_req_zone in http block for rate-limited routes', () => {
    const r = { ...baseRoute, advanced_json: { rate_limit_req_per_sec: 5 } }
    const { 'nginx.conf': conf } = renderConfig({ routes: [r], fileRoutes: [] }, STAGING)
    expect(conf).toContain('limit_req_zone $binary_remote_addr')
    expect(conf).toContain('rate=5r/s')
    // Must appear before the server block
    const httpIdx = conf.indexOf('http {')
    const serverIdx = conf.indexOf('server {')
    const zoneIdx = conf.indexOf('limit_req_zone')
    expect(zoneIdx).toBeGreaterThan(httpIdx)
    expect(zoneIdx).toBeLessThan(serverIdx)
  })
})

describe('rateLimitZoneName', () => {
  it('replaces hyphens with underscores', () => {
    expect(rateLimitZoneName('abc-def-ghi')).toBe('rl_abc_def_ghi')
  })
})
