import type { Route, FileRoute, AdvancedJson } from '@unginx/shared'
import { STAGING_DIR, LOGS_DIR } from '@unginx/shared'

const LOG_FORMAT_NAME = 'unginx_combined'

export const LOG_FORMAT_DECLARATION =
  `log_format ${LOG_FORMAT_NAME} '$remote_addr - $remote_user [$time_local] '\n` +
  `                           '"$request" $status $body_bytes_sent '\n` +
  `                           '"$http_referer" "$http_user_agent" '\n` +
  `                           'rid=$unginx_route_id rt=$request_time';`

export interface RenderState {
  routes: Route[]
  fileRoutes: FileRoute[]
}

export interface RenderResult {
  'routes.conf': string
  'files.conf': string
  'nginx.conf': string
}

export function renderConfig(
  state: RenderState,
  stagingDir: string = STAGING_DIR
): RenderResult {
  const ts = new Date().toISOString()
  const enabledRoutes = state.routes.filter((r) => r.enabled)
  const enabledFileRoutes = state.fileRoutes.filter((fr) => fr.enabled)

  return {
    'routes.conf': renderRoutes(enabledRoutes, ts),
    'files.conf': renderFileRoutes(enabledFileRoutes, ts),
    'nginx.conf': renderStagingNginxConf(enabledRoutes, stagingDir, ts),
  }
}

function parseAdvanced(raw: AdvancedJson | string): AdvancedJson {
  if (typeof raw === 'string') {
    try {
      return JSON.parse(raw) as AdvancedJson
    } catch {
      return {}
    }
  }
  return raw
}

function renderRoutes(routes: Route[], ts: string): string {
  const lines: string[] = [
    `# AUTO-GENERATED by unginx — do not edit by hand.`,
    `# Generated at: ${ts}`,
    ``,
  ]

  for (const route of routes) {
    const adv = parseAdvanced(route.advanced_json)
    const upstream = `${route.upstream_scheme}://${route.upstream_host}:${route.upstream_port}`

    lines.push(`# --- Route: "${route.name}" ---`)
    lines.push(`location ${route.path} {`)
    lines.push(`    set $unginx_route_id "${route.id}";`)
    lines.push(`    access_log ${LOGS_DIR}/access.log ${LOG_FORMAT_NAME};`)
    lines.push(``)
    lines.push(`    proxy_pass ${upstream};`)
    lines.push(`    proxy_http_version 1.1;`)
    lines.push(`    proxy_set_header Host              $host;`)
    lines.push(`    proxy_set_header X-Real-IP         $remote_addr;`)
    lines.push(`    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;`)
    lines.push(`    proxy_set_header X-Forwarded-Proto $scheme;`)

    if (route.websocket) {
      lines.push(`    proxy_set_header Upgrade           $http_upgrade;`)
      lines.push(`    proxy_set_header Connection        "upgrade";`)
    }

    if (adv.client_max_body_size_mb) {
      lines.push(`    client_max_body_size ${adv.client_max_body_size_mb}m;`)
    }
    if (adv.proxy_read_timeout_s) {
      lines.push(`    proxy_read_timeout ${adv.proxy_read_timeout_s}s;`)
    }
    if (adv.proxy_connect_timeout_s) {
      lines.push(`    proxy_connect_timeout ${adv.proxy_connect_timeout_s}s;`)
    }
    for (const h of adv.request_headers ?? []) {
      lines.push(
        `    proxy_set_header ${sanitizeHeaderName(h.name)} "${escapeHeaderValue(h.value)}";`
      )
    }
    for (const h of adv.response_headers ?? []) {
      lines.push(
        `    add_header ${sanitizeHeaderName(h.name)} "${escapeHeaderValue(h.value)}";`
      )
    }
    if (adv.rate_limit_req_per_sec && adv.rate_limit_req_per_sec > 0) {
      const zone = rateLimitZoneName(route.id)
      lines.push(
        `    limit_req zone=${zone} burst=${adv.rate_limit_req_per_sec * 2} nodelay;`
      )
    }

    lines.push(`}`)
    lines.push(``)
  }

  return lines.join('\n')
}

function renderFileRoutes(fileRoutes: FileRoute[], ts: string): string {
  const lines: string[] = [
    `# AUTO-GENERATED by unginx — do not edit by hand.`,
    `# Generated at: ${ts}`,
    ``,
  ]

  for (const fr of fileRoutes) {
    const adv = parseAdvanced(fr.advanced_json)
    const folderPath = fr.folder_path.endsWith('/') ? fr.folder_path : `${fr.folder_path}/`

    lines.push(`location ${fr.path} {`)
    lines.push(`    set $unginx_route_id "${fr.id}";`)
    lines.push(`    access_log ${LOGS_DIR}/access.log ${LOG_FORMAT_NAME};`)
    lines.push(``)
    lines.push(`    alias ${folderPath};`)
    lines.push(`    index ${fr.index_files};`)

    if (fr.spa_mode) {
      lines.push(`    try_files $uri $uri/ /index.html;`)
    } else if (fr.try_files) {
      lines.push(`    try_files $uri $uri/ ${fr.try_files};`)
    } else {
      lines.push(`    try_files $uri $uri/ =404;`)
    }

    lines.push(`    autoindex ${fr.dir_listing ? 'on' : 'off'};`)

    for (const h of adv.response_headers ?? []) {
      lines.push(
        `    add_header ${sanitizeHeaderName(h.name)} "${escapeHeaderValue(h.value)}";`
      )
    }

    lines.push(`}`)
    lines.push(``)
  }

  return lines.join('\n')
}

function renderStagingNginxConf(
  routes: Route[],
  stagingDir: string,
  ts: string
): string {
  const rateLimitZones: string[] = []
  for (const route of routes) {
    const adv = parseAdvanced(route.advanced_json)
    if (adv.rate_limit_req_per_sec && adv.rate_limit_req_per_sec > 0) {
      const zone = rateLimitZoneName(route.id)
      rateLimitZones.push(
        `    limit_req_zone $binary_remote_addr zone=${zone}:10m rate=${adv.rate_limit_req_per_sec}r/s;`
      )
    }
  }

  const rlBlock =
    rateLimitZones.length > 0 ? '\n' + rateLimitZones.join('\n') + '\n' : ''

  return [
    `# AUTO-GENERATED by unginx — staging test config only, not used at runtime.`,
    `# Generated at: ${ts}`,
    ``,
    `events {`,
    `    worker_connections 1024;`,
    `}`,
    ``,
    `http {`,
    `    ${LOG_FORMAT_DECLARATION}`,
    rlBlock,
    `    server {`,
    `        listen 127.0.0.1:18080;`,
    `        server_name _;`,
    ``,
    `        include ${stagingDir}/routes.conf;`,
    `        include ${stagingDir}/files.conf;`,
    ``,
    `        location / {`,
    `            default_type text/plain;`,
    `            return 404 "No route configured at this path.\\n";`,
    `        }`,
    `    }`,
    `}`,
  ].join('\n')
}

export function rateLimitZoneName(routeId: string): string {
  return `rl_${routeId.replace(/-/g, '_')}`
}

function sanitizeHeaderName(name: string): string {
  return name.replace(/[^A-Za-z0-9\-_]/g, '')
}

function escapeHeaderValue(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}
